// <auto-generated />
using Ginga_Alexandra_Labo2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using System.Net.NetworkInformation;

namespace Ginga_Alexandra_Labo2.Migrations
    {
        public partial class BookData : Migration
        {
            protected override void Up(MigrationBuilder migrationBuilder)
            {

            }

            protected override void Down(MigrationBuilder migrationBuilder)
            {

            }
        }
    }

